-- Basic
require("core.plugins")
require("core.mappings")
require("core.configs")
require("core.colors")

-- Plugins
require("plugins.neotree")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.mason")
require("plugins.telescope")
require("plugins.null-ls")
require("plugins.autotag")
require("plugins.buffline")
require("plugins.comment")
require("plugins.gitsigns")
require("plugins.which-key")
require("plugins.copilot")
require("plugins.surround")
require("plugins.lualine")
