return {
	"bash-language-server",
	"shfmt",
	"clangd",
	"rust-analyzer",
	"eslint_d",
	"emmet-ls",
	"html-lsp",
	"css-lsp",
	"prettier",
	-- "prettierd",
	"typescript-language-server",
	"vue-language-server",
	"jdtls",
	"google-java-format",
	"lua-language-server",
	"stylua",
}
